version: "3.9"

services:
  chat_service:
    container_name: chat_service
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    # NOTE: Add profile to this service to easily identify it for the up and
    # down commands
    profiles:
      - server
    ports:
      - "9000:9000"
    networks:
      - chat
    environment:
      DB_CONNECTION_STRING: postgres://postgres:postgres@chat_db:5432/chat
      PORT: 9000
      JWT_SECRET_KEY: secret

    depends_on:
      chat_db:
        condition: service_healthy
  chat_db:
    container_name: chat_database
    image: postgres:13.3-alpine
    restart: always
    networks:
      - chat
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres -d chat
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  chat:
    driver: bridge
