# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkg/protobuf/auth_service/auth_service.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'pkg/protobuf/auth_service/auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,pkg/protobuf/auth_service/auth_service.proto\x12\x07\x61uth.v1\x1a\x1bgoogle/protobuf/empty.proto\"H\n\rSignUpRequest\x12\x1b\n\tuser_name\x18\x01 \x01(\tR\x08userName\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\")\n\x0eSignUpResponse\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\"H\n\rSignInRequest\x12\x1b\n\tuser_name\x18\x01 \x01(\tR\x08userName\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"L\n\x0eSignInResponse\x12\x17\n\x07user_id\x18\x01 \x01(\tR\x06userId\x12!\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\tR\x0b\x61\x63\x63\x65ssToken2\xc4\x01\n\x0b\x41uthService\x12;\n\x06SignUp\x12\x16.auth.v1.SignUpRequest\x1a\x17.auth.v1.SignUpResponse\"\x00\x12;\n\x06SignIn\x12\x16.auth.v1.SignInRequest\x1a\x17.auth.v1.SignInResponse\"\x00\x12;\n\x07SignOut\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x42\\\n\x0b\x63om.auth.v1B\x10\x41uthServiceProtoP\x01\xa2\x02\x03\x41XX\xaa\x02\x07\x41uth.V1\xca\x02\x07\x41uth\\V1\xe2\x02\x13\x41uth\\V1\\GPBMetadata\xea\x02\x08\x41uth::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.protobuf.auth_service.auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.auth.v1B\020AuthServiceProtoP\001\242\002\003AXX\252\002\007Auth.V1\312\002\007Auth\\V1\342\002\023Auth\\V1\\GPBMetadata\352\002\010Auth::V1'
  _globals['_SIGNUPREQUEST']._serialized_start=86
  _globals['_SIGNUPREQUEST']._serialized_end=158
  _globals['_SIGNUPRESPONSE']._serialized_start=160
  _globals['_SIGNUPRESPONSE']._serialized_end=201
  _globals['_SIGNINREQUEST']._serialized_start=203
  _globals['_SIGNINREQUEST']._serialized_end=275
  _globals['_SIGNINRESPONSE']._serialized_start=277
  _globals['_SIGNINRESPONSE']._serialized_end=353
  _globals['_AUTHSERVICE']._serialized_start=356
  _globals['_AUTHSERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
