# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pkg.protobuf.auth_service import auth_service_pb2 as pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignUp = channel.unary_unary(
                '/auth.v1.AuthService/SignUp',
                request_serializer=pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignUpRequest.SerializeToString,
                response_deserializer=pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignUpResponse.FromString,
                _registered_method=True)
        self.SignIn = channel.unary_unary(
                '/auth.v1.AuthService/SignIn',
                request_serializer=pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignInRequest.SerializeToString,
                response_deserializer=pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignInResponse.FromString,
                _registered_method=True)
        self.SignOut = channel.unary_unary(
                '/auth.v1.AuthService/SignOut',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignUpRequest.FromString,
                    response_serializer=pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignUpResponse.SerializeToString,
            ),
            'SignIn': grpc.unary_unary_rpc_method_handler(
                    servicer.SignIn,
                    request_deserializer=pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignInRequest.FromString,
                    response_serializer=pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignInResponse.SerializeToString,
            ),
            'SignOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SignOut,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.AuthService/SignUp',
            pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignUpRequest.SerializeToString,
            pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.AuthService/SignIn',
            pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignInRequest.SerializeToString,
            pkg_dot_protobuf_dot_auth__service_dot_auth__service__pb2.SignInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.v1.AuthService/SignOut',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
