# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pkg.protobuf.chat_service import chat_service_pb2 as pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Send = channel.unary_unary(
                '/chat.v1.ChatService/Send',
                request_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SendRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMessage = channel.unary_unary(
                '/chat.v1.ChatService/GetMessage',
                request_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.GetMessageRequest.SerializeToString,
                response_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Message.FromString,
                _registered_method=True)
        self.React = channel.unary_unary(
                '/chat.v1.ChatService/React',
                request_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.ReactionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetReaction = channel.unary_unary(
                '/chat.v1.ChatService/GetReaction',
                request_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.GetReactionRequest.SerializeToString,
                response_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Reaction.FromString,
                _registered_method=True)
        self.Fetch = channel.unary_stream(
                '/chat.v1.ChatService/Fetch',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Message.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/chat.v1.ChatService/Subscribe',
                request_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SubscribeResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/chat.v1.ChatService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Send(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def React(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fetch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SendRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.GetMessageRequest.FromString,
                    response_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Message.SerializeToString,
            ),
            'React': grpc.unary_unary_rpc_method_handler(
                    servicer.React,
                    request_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.ReactionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReaction,
                    request_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.GetReactionRequest.FromString,
                    response_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Reaction.SerializeToString,
            ),
            'Fetch': grpc.unary_stream_rpc_method_handler(
                    servicer.Fetch,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Message.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SubscribeRequest.FromString,
                    response_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SubscribeResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.v1.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.v1.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/Send',
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SendRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/GetMessage',
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.GetMessageRequest.SerializeToString,
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def React(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/React',
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.ReactionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/GetReaction',
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.GetReactionRequest.SerializeToString,
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Reaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fetch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.v1.ChatService/Fetch',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.v1.ChatService/Subscribe',
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SubscribeRequest.SerializeToString,
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.SubscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.v1.ChatService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pkg_dot_protobuf_dot_chat__service_dot_chat__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
